# Generated by Django 3.1.1 on 2020-09-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200919_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
